{{- if .Values.ingress.enabled -}}
{{- $serviceName := .Values.name -}}
{{- $svcPort := .Values.service.port -}}
{{- $svcName := .Values.name  -}}
{{- range .Values.ingress.ingresses }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $serviceName }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
    {{- range .hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
---
  {{- end }}
{{- end }}