{{- if .Values.podDisruption.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.podDisruption.name }}
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ .Values.podDisruption.minAvailable }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
{{- end }}