{{- if .Values.podDisruption.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: springservice-pdb
  namespace: production
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: springservice
{{- end }}