name: "springservice"
namespace: "production"
replicaCount: 2
executeCommand: "java -jar /app/app.jar"

image:
  repository: hub.docker.com/repository/docker/alicanuzun/springboot
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

minAvailable: 2

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

probe:
  enabled: false
  livenessPath: /health
  readinessPath: /health

ingress:
  enabled: false
  ingresses:
    - name: springapp
      annotations:
      hosts:
        - host: 10.50.0.10:8080
          paths:
            - "/"
        - host: 10.50.0.11:8080
          paths:
            - "/"
        - host: 10.50.0.12:8080
          paths:
            - "/"
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 1000Mi
  requests:
    cpu: 100m
    memory: 200Mi

autoscaling:
  enabled: false
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-type
          operator: In
          values:
          - worker