name: "springservice"
namespace: "production"
replicaCount: 4
executeCommand: "java -jar /app/app.jar"

image:
  repository: alicanuzun/springservice
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: 
  - name: regcred

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podDisruption:
  enabled: true
  minAvailable: 2

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

probe:
  enabled: false
  livenessPath: /health
  readinessPath: /health

ingress:
  enabled: true
  ingresses:
    - name: springapp
      annotations:
      hosts:
        - host: springservice.com
          paths:
            - "/"
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 1000Mi
  requests:
    cpu: 100m
    memory: 200Mi

autoscaling:
  enabled: false
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-type
          operator: In
          values:
          - worker